language: go

go:
  - 1.8
  - tip

sudo: required

env:
  global:
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - ORACLE_COOKIE=ic_linuxx8664
    - PKG_CONFIG_PATH="."
    - ORACLE_DOWNLOAD_DIR=.cache/oracle

before_install:
  - wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz'
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - ORACLE_FILE='instantclient/11204/oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm'
  - .travis/oracle/download.sh
  - ls -R .cache/oracle
  - .travis/oracle/install.sh
  - ORACLE_FILE='instantclient/11204/oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm'
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - ORACLE_FILE='instantclient/11204/oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm'
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - >
    { echo "Name: oci8"; echo "Description: Oracle Call Interface"; echo "Version: 11.2";
      echo "Cflags: -I/usr/include/oracle/11.2/client64/";
      echo "Libs: -L$ORACLE_HOME/lib -Wl,-rpath,$ORACLE_HOME/lib -lclntsh";
    } | tee oci8.pc
  - go get github.com/mattn/go-oci8

script:
  - make style
  - make vet
  - make test
  - make build

matrix:
  allow_failures:
    - go: tip
