language: go

go:
  - 1.8
  - tip

sudo: required

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - ORACLE_COOKIE=ic_linuxx8664
    - PKG_CONFIG_PATH="."

before_install:
  - wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz'
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - export=ORACLE_HOME=instantclient/112010/oracle-instantclient11.2-sdk-11.2.0.1.0-1.x86_64.zip
  - .travis/oracle/download.sh
  - unzip oracle-instantclient11.2-sdk-11.2.0.1.0-1.x86_64.zip
  - ls -R oracle-instantclient11.2-sdk-11.2.0.1.0-1.x86_64
  - ls -R /u01/app/oracle/product/11.2.0/xe/lib
  - >
    { echo "Name: oci8"; echo "Description: Oracle Call Interface"; echo "Version: 11.2";
      echo "Cflags: -I$ORACLE_HOME/rdbms/public";
      echo "Libs: -L$ORACLE_HOME/lib -Wl,-rpath,$ORACLE_HOME/lib -lclntsh";
    } | tee oci8.pc
  - go get github.com/mattn/go-oci8

script:
  - make style
  - make vet
  - make test
  - make build

matrix:
  allow_failures:
    - go: tip
