language: go

go:
  - 1.8
  - tip

sudo: required

env:
  global:
    - ORACLE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - PKG_CONFIG_PATH="."

before_install:
  - go get -d github.com/mattn/go-oci8
  - $HOME/gopath/src/github.com/mattn/go-oci8/.travis/oracle/download.sh
  - $HOME/gopath/src/github.com/mattn/go-oci8/.travis/oracle/install.sh
  - >
    { echo "Name: oci8"; echo "Description: Oracle Call Interface"; echo "Version: 11.1";
      echo "Cflags: -I$ORACLE_HOME/rdbms/public";
      echo "Libs: -L$ORACLE_HOME/lib -Wl,-rpath,$ORACLE_HOME/lib -lclntsh";
    } | tee oci8.pc
  - go install github.com/mattn/go-oci8

script:
  - make style
  - make vet
  - make test
  - make build

matrix:
  allow_failures:
    - go: tip
