FROM golang:1.8-alpine

RUN apk --update add \
  ca-certificates \
  gcc \
  git \
  make \
  musl-dev \
  && rm -rf /var/cache/apk/*

ENV GOPATH /go
ENV GOBIN $GOPATH/bin
ENV PATH $GOBIN:$PATH

RUN mkdir -p "$GOPATH/src" "$GOBIN" && chmod -R 777 "$GOPATH"
RUN go get -u github.com/golang/lint/golint
RUN go get -u github.com/FiloSottile/vendorcheck
RUN go get -u honnef.co/go/tools/cmd/gosimple
RUN go get -u honnef.co/go/tools/cmd/staticcheck

ADD .   /go/src/github.com/sql_exporter
WORKDIR /go/src/github.com/sql_exporter

RUN make install
EXPOSE 8080
